name: Sufi-Al-Hussaini
description: Senior Software Developer | Urdu Sufi Poet
meta_description: "Shoaib Ahmed is a system software developer, urdu Sufi poet and self-proclaimed philosopher. He writes under the nom-de-plume of 'Sufi-Al-Hussaini'."

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://shoaib-ahmed.com'
google_analytics: 'UA-66607718-1'
disqus: true
disqus_shortname: 'sufialhussaini'

# Details for the RSS feed generator
url:            'http://shoaib-ahmed.com'
author:         'Shoaib Ahmed'
authorTwitter:  'sufi-al-hussaini'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
